fastlane_version "2.28.7"
default_platform :ios

platform :ios do
  # before_all do
  #   # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  #
  #   carthage
  # end

  lane :beta do
    gym(scheme: "LJ STAND")
    pilot
  end

  lane :release do
    gym(scheme: "LJ STAND")
    deliver(force: true)
  end
end
